//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firefly.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firefly.Localization.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Borderless + Always on top 的本地化字符串。
        /// </summary>
        internal static string BorderlessAndAlwaysOnTop {
            get {
                return ResourceManager.GetString("BorderlessAndAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to new Live2D window 的本地化字符串。
        /// </summary>
        internal static string ClickToNewLive2DWindow {
            get {
                return ResourceManager.GetString("ClickToNewLive2DWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not show again 的本地化字符串。
        /// </summary>
        internal static string DoNotShowAgain {
            get {
                return ResourceManager.GetString("DoNotShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading Windows App Runtime 的本地化字符串。
        /// </summary>
        internal static string DownloadingWindowsAppRuntime {
            get {
                return ResourceManager.GetString("DownloadingWindowsAppRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download manually 的本地化字符串。
        /// </summary>
        internal static string DownloadManually {
            get {
                return ResourceManager.GetString("DownloadManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download or installation failed. 的本地化字符串。
        /// </summary>
        internal static string DownloadOrInstallationFailed {
            get {
                return ResourceManager.GetString("DownloadOrInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install required components. 的本地化字符串。
        /// </summary>
        internal static string InstallRequiredComponents {
            get {
                return ResourceManager.GetString("InstallRequiredComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License 的本地化字符串。
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live2D model 的本地化字符串。
        /// </summary>
        internal static string Live2DModel {
            get {
                return ResourceManager.GetString("Live2DModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mirror 的本地化字符串。
        /// </summary>
        internal static string Mirror {
            get {
                return ResourceManager.GetString("Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Live2D window 的本地化字符串。
        /// </summary>
        internal static string NewLive2DWindow {
            get {
                return ResourceManager.GetString("NewLive2DWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version 的本地化字符串。
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All contents of this software are intended for personal learning use only. Any form of commercial use or obtaining economic benefits from it is strictly prohibited. 的本地化字符串。
        /// </summary>
        internal static string NonCommercialDeclaration {
            get {
                return ResourceManager.GetString("NonCommercialDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity 的本地化字符串。
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place the cute Firefly on the desktop. 的本地化字符串。
        /// </summary>
        internal static string PlaceTheCuteFireflyOnTheDesktop {
            get {
                return ResourceManager.GetString("PlaceTheCuteFireflyOnTheDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play / Pause 的本地化字符串。
        /// </summary>
        internal static string PlayPause {
            get {
                return ResourceManager.GetString("PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random emotion 的本地化字符串。
        /// </summary>
        internal static string RandomEmotion {
            get {
                return ResourceManager.GetString("RandomEmotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right-click in the Live2D window to open the menu. 的本地化字符串。
        /// </summary>
        internal static string RightClickInTheLive2DWindowToOpenTheMenu {
            get {
                return ResourceManager.GetString("RightClickInTheLive2DWindowToOpenTheMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source code 的本地化字符串。
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This program requires Windows 10 version 1809 (build 17763) or later to run. 的本地化字符串。
        /// </summary>
        internal static string SystemVersionTip {
            get {
                return ResourceManager.GetString("SystemVersionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window mode 的本地化字符串。
        /// </summary>
        internal static string WindowMode {
            get {
                return ResourceManager.GetString("WindowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string 关闭 {
            get {
                return ResourceManager.GetString("关闭", resourceCulture);
            }
        }
    }
}
